[[constraint]]
  name = "github.com/giantswarm/k8sclient"
  branch = "master"

[[constraint]]
  name = "github.com/giantswarm/microendpoint"
  branch = "master"

[[constraint]]
  name = "github.com/giantswarm/microerror"
  branch = "master"

[[constraint]]
  name = "github.com/giantswarm/microkit"
  branch = "master"

[[constraint]]
  name = "github.com/giantswarm/microclient"
  branch = "master"

[[constraint]]
  name = "github.com/giantswarm/micrologger"
  branch = "master"

[[constraint]]
  name = "github.com/giantswarm/operatorkit"
  branch = "master"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.2"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.16.3"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.16.3"

[[constraint]]
  name = "gopkg.in/resty.v1"
  version = "=v1.12.0"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.16.3"



[prune]
  go-tests = true
  unused-packages = true
