[[constraint]]
  branch = "master"
  name = "github.com/giantswarm/microendpoint"

[[constraint]]
  branch = "master"
  name = "github.com/giantswarm/microerror"

[[constraint]]
  branch = "master"
  name = "github.com/giantswarm/microkit"

[[constraint]]
  branch = "master"
  name = "github.com/giantswarm/microclient"

[[constraint]]
  branch = "master"
  name = "github.com/giantswarm/micrologger"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.2"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.15.4"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.15.4"

[[constraint]]
  name = "gopkg.in/resty.v1"
  version = "=v1.12.0"



[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.15.4"



[prune]
  go-tests = true
  unused-packages = true
