apiVersion: v1
kind: ConfigMap
metadata:
  name: credentiald-configmap
  namespace: giantswarm
data:
  config.yml: |
    server:
      enable:
        debug:
          server: true
      listen:
        address: 'http://0.0.0.0:8000'
