{{- if .Values.Installation.V1.Secret.Credentiald }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: credential-default
  namespace: giantswarm
  labels:
    app: credentiald
    giantswarm.io/managed-by: credentiald
    giantswarm.io/organization: giantswarm
    giantswarm.io/service-type: system
data:
  {{- if .Values.Installation.V1.Secret.Credentiald.AWS }}
  aws.admin.arn: {{ .Values.Installation.V1.Secret.Credentiald.AWS.CredentialDefault.AdminARN | b64enc | quote }}
  aws.awsoperator.arn: {{ .Values.Installation.V1.Secret.Credentiald.AWS.CredentialDefault.AWSOperatorARN | b64enc | quote }}
  {{- end }}
  {{- if .Values.Installation.V1.Secret.Credentiald.Azure }}
  azure.azureoperator.clientid: {{ .Values.Installation.V1.Secret.Credentiald.Azure.CredentialDefault.ClientID | b64enc | quote }}
  azure.azureoperator.clientsecret: {{ .Values.Installation.V1.Secret.Credentiald.Azure.CredentialDefault.ClientSecret | b64enc | quote }}
  azure.azureoperator.subscriptionid: {{ .Values.Installation.V1.Secret.Credentiald.Azure.CredentialDefault.SubscriptionID | b64enc | quote }}
  azure.azureoperator.tenantid: {{ .Values.Installation.V1.Secret.Credentiald.Azure.CredentialDefault.TenantID | b64enc | quote }}
  {{- end }}
{{- end }}
