{{- if .Values.credentiald }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: credential-default
  namespace: giantswarm
  labels:
    app: credentiald
    giantswarm.io/managed-by: credentiald
    giantswarm.io/organization: giantswarm
    giantswarm.io/service-type: system
data:
  {{- if .Values.credentiald.aws }}
  aws.admin.arn: {{ .Values.credentiald.aws.defaultCredentials.adminARN | b64enc | quote }}
  aws.awsoperator.arn: {{ .Values.credentiald.aws.credentialdDefault.awsOperatorARN | b64enc | quote }}
  {{- end }}
  {{- if .Values.credentiald.azure }}
  azure.azureoperator.clientid: {{ .Values.credentiald.azure.defaultCredentials.clientID | b64enc | quote }}
  azure.azureoperator.clientsecret: {{ .Values.credentiald.azure.defaultCredentials.clientSecret | b64enc | quote }}
  azure.azureoperator.subscriptionid: {{ .Values.credentiald.azure.defaultCredentials.subscriptionID | b64enc | quote }}
  azure.azureoperator.tenantid: {{ .Values.credentiald.azure.defaultCredentials.tenantID | b64enc | quote }}
  {{- end }}
{{- end }}
