{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: credentiald
  namespace: giantswarm
  labels:
    app: credentiald
    application.giantswarm.io/team: {{ index .Chart.Annotations "application.giantswarm.io/team" | quote }}
spec:
  endpoints:
    - interval: {{ .Values.serviceMonitor.interval }}
      path: /metrics
      port: http
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
  selector:
    matchLabels:
      app: credentiald
{{- end }}
