apiVersion: v1
kind: Service
metadata:
  name: credentiald
  namespace: giantswarm
  labels:
    app: credentiald
  annotations:
    prometheus.io/scrape: "true"
spec:
  ports:
  - port: 8000
  selector:
    app: credentiald
