version: 2.1
orbs:
  architect: giantswarm/architect@2.4.2

workflows:
  build:
    jobs:
      - architect/go-build:
          name: build-credentiald
          context: architect
          binary: credentiald
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          name: push-credentiald-to-quay
          context: architect
          image: "quay.io/giantswarm/credentiald"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - build-credentiald
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          name: push-credentiald-to-aliyun
          context: architect
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/credentiald"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          requires:
            - build-credentiald
          # Needed to trigger job only on git tag.
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          name: push-credentiald-to-control-plane-app-catalog
          context: architect
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "credentiald"
          requires:
            - push-credentiald-to-quay
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-credentiald-to-aws-app-collection
          context: architect
          app_name: "credentiald"
          app_collection_repo: "aws-app-collection"
          requires:
            - push-credentiald-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-credentiald-to-azure-app-collection
          context: architect
          app_name: "credentiald"
          app_collection_repo: "azure-app-collection"
          requires:
            - push-credentiald-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-credentiald-to-kvm-app-collection
          context: architect
          app_name: "credentiald"
          app_collection_repo: "kvm-app-collection"
          requires:
            - push-credentiald-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

