version: 2.1
orbs:
  architect: giantswarm/architect@5.15.0

workflows:
  build:
    jobs:
    - architect/go-build:
        name: build-credentiald
        context: architect
        binary: credentiald
        filters:
          tags:
            only: /^v.*/

    - architect/push-to-registries:
        context: architect
        name: push-to-registries
        requires:
        - build-credentiald
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore:
            - main
            - master

    - architect/push-to-app-catalog:
        name: push-credentiald-to-control-plane-app-catalog
        context: architect
        app_catalog: control-plane-catalog
        app_catalog_test: control-plane-test-catalog
        chart: credentiald
        requires:
        - push-to-registries
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore:
            - main
            - master
