image:
  repository: giantswarm/credentiald
  tag: [[ .Version ]]
deployment:
  replicas: 2
pod:
  user:
    id: 1000
  group:
    id: 1000

registry:
  domain: docker.io

provider:
  aws:
    defaultCredentials:
      adminARN: ""
      awsOperatorARN: ""
  azure:
    defaultCredentials:
      clientID: ""
      clientSecret: ""
      subscriptionID: ""
      tenantID: ""
