apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: credentiald-network-policy
  namespace: giantswarm
spec:
  podSelector:
    matchLabels:
      app: credentiald
  policyTypes:
  - Ingress
  - Egress
  # Allow access only from api server.
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: api
    ports:
    - protocol: TCP
      port: 8000
  # Allow all egress traffic.
  egress:
  - {}
