# Allow create secrets in giantswarm namespace.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: credentiald
  namespace: giantswarm
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: credentiald
  namespace: giantswarm
subjects:
  - kind: ServiceAccount
    name: credentiald
    namespace: giantswarm
roleRef:
  kind: Role
  name: credentiald
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: credentiald-psp
  namespace: giantswarm
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - credentiald-psp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: credentiald-psp
  namespace: giantswarm
subjects:
  - kind: ServiceAccount
    name: credentiald
    namespace: giantswarm
roleRef:
  kind: Role
  name: credentiald-psp
  apiGroup: rbac.authorization.k8s.io
